### ISSUE TITLE
Hello，where is the source code?

### ISSUE THREAD

**Issue by MU0** [deezer/sigir23-mojito#1]

**Comment by zyx1017** [comment]
same as here

**Comment by 0xpi** [comment]
Hello, thank you very much for your interest. Sorry for a little bit late due to the work load right now for other conference. The source code will be available in the next few days.

**Comment by 869277160** [comment]
Two weeks have passed, yet no codes have been published.

**Comment by arnold-em** [comment]
sorry ，the code will come soon.



---- Replied Message ----
| From | ***@***.***> |
| Date | 05/16/2023 16:10 |
| To | ***@***.***> |
| Cc | ***@***.***> |
| Subject | Re: [deezer/sigir23-mojito] Hello，where is the source code? (Issue #1) |

Two weeks have passed, yet no codes have been published.

**Comment by 0xpi** [comment]
Hello, thank you again for your interest and sorry for this late. We've just pushed our code to this repo.

**Comment by 869277160** [comment]
Special thanks for your codes and work, your idea of incorporating temporal information for user modeling was constructive for me.

**Comment by GoodTimeNET** [comment]
> Special thanks for your codes and work, your idea of incorporating temporal information for user modeling was constructive for me.
大佬，你代码跑通了吗？ 我遇到了一些问题。

**Comment by Lyla-yanling** [comment]
> > Special thanks for your codes and work, your idea of incorporating temporal information for user modeling was constructive for me.
> > 大佬，你代码跑通了吗？ 我遇到了一些问题。
你跑通了吗？我也遇到一些问题，可以交流下吗

**Comment by GoodTimeNET** [comment]
qq 278697796




甜甜的咸鱼
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deezer/sigir23-mojito"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deezer/sigir23-mojito] Hello，where is the source code? (Issue #1)





   
Special thanks for your codes and work, your idea of incorporating temporal information for user modeling was constructive for me.
 大佬，你代码跑通了吗？ 我遇到了一些问题。
 你跑通了吗？我也遇到一些问题，可以交流下吗

**Comment by GuillaumeSalhaGalvan** [comment]
Dear all, 

Thank you very much for your interest.

I am closing this issue now, as our lead author Viet-Anh Tran (@0xpi) released his source code.

However, feel free to contact us and/or open another issue if you have questions on specific aspects of the model.
(最好是用英语，但我们也可以尝试理解中文。:wink: )

Best regards,

Guillaume

**Comment by GoodTimeNET** [comment]
qq 忘记你好友名字了，我想问你一下&nbsp;sigir23-mojito三个数据集你都跑过了吗? github上第三个数据集有问题，我要吐血了。




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "deezer/sigir23-mojito"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2023年6月29日(星期四) 下午4:25
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [deezer/sigir23-mojito] Hello，where is the source code? (Issue #1)





   
Special thanks for your codes and work, your idea of incorporating temporal information for user modeling was constructive for me.
 大佬，你代码跑通了吗？ 我遇到了一些问题。
 你跑通了吗？我也遇到一些问题，可以交流下吗
