### ISSUE TITLE
About data preprocessing

### ISSUE THREAD

**Issue by Lyla-yanling** [deezer/sigir23-mojito#2]
hello ! The code needs  .csv  file, can you give a sample file to show me how to preprocess the raw data?

**Comment by 0xpi** [comment]
Hello, sorry we forgot to delete the preprocessed file before testing from scratch. We've added the preprocess script in data_misc directory. This script should be run before the training command. Thanks !

**Comment by GoodTimeNET** [comment]
> hello ! The code needs .csv file, can you give a sample file to show me how to preprocess the raw data?

你第三个数据集 跑通了吗

**Comment by Gs0098** [comment]
> hello ! The code needs .csv file, can you give a sample file to show me how to preprocess the raw data?你好！代码需要.csv 文件，你能给我一个样本文件来展示如何预处理原始数据吗？

这个只能tensorflow嘛
